### ISSUE TITLE
Resize Sankey

### ISSUE THREAD

**Issue by silvaRodrigues** [dbk4002/angular-google-chart#1]
I want to resize the sankey chart, but it has a custom div that i can't change.

**Comment by dbk4002** [comment]
Hello @silvaRodrigues ,

You can pass options attribute to component to provide height and width.

` let SANKEY_OPTIONS = {
      width: 600,
      height: 900
    };`

`<google-chart [chartType]="'Sankey'" [dataPromise]="dataMap['SANKEY_DATA']"  [options] ="SANKEY_OPTIONS'" ></google-chart>`

Let me know if it works for you. Feel free to reopen this if it wont solve problem.

**Comment by silvaRodrigues** [comment]
Solution:

**demo.ts**
`
let SANKEY_OPTIONS= { width: 800, height: 700};
this.dataMap['SANKEY_DATA'] =  loadData(SANKEY_DATA);
this.dataMap['SANKEY_OPTIONS'] =  SANKEY_OPTIONS;
`
**demo.html**
`<google-chart [chartType]="'Sankey'" [dataPromise]="dataMap['SANKEY_DATA']" [options]="dataMap['SANKEY_OPTIONS']" ></google-chart>`

Thank you @dbk4002 !
